package it.polimi.ingsw.network.Message;

public enum MessageType {
    LOGIN_REQUEST,
    LOGIN_REPLY,
    NUM_OF_PLAYERS_REQUEST,
    NUM_OF_PLAYERS_REPLY,
    PICK_FIRST_PLAYER,
    DISCONNECTION_REQUEST,
    DISCONNECTION_REPLY,
    PING,
    ACK,
    TILES_REQUEST,
    INSERT_TILES,
    COLUMN_REQUEST,
    COLUMN,
    UPDATE_POINTS,
    GENERIC_MESSAGE,
    WINNER



}
